#!/usr/bin/env python3
"""Which sections of a CFR part does Oregon actually cite? -> _meta/cited-sections/<part>.yml

    python3 src/scan_cited_sections.py --erf ../executive-regulatory-frameworks --audits ../oregon-audits \
        --title 2 --part 200

The operator decision for this corpus was "split only what is cited", so the split list is
DERIVED rather than chosen. This script derives it, per PART, and writes it to
`_meta/cited-sections/<title>-cfr-<part>.yml`, which is committed and reviewed.

#34: `--title`/`--part` used to be implicit -- a literal `2` and `200.` baked into every
regex here, so the only part this script could ever measure was 2 CFR 200. Every big
instrument gets the identical demand-driven treatment now (see the STANDING TRIGGER note
below): the regexes are BUILT from whatever (title, part) is passed, and the short-form
disambiguation guard -- count `§NNN.MM` only in a file that also carries the full citation
elsewhere -- is the same per-part-derived mechanism it always was, now actually applied per
part instead of hardcoded to 200's collision with ORS chapter 200. #27's own triage (see
that issue) found the SAME guard is not marginal for 45 CFR 164: ORS chapter 164 (theft and
burglary) is the MORE common meaning of a bare `164.NNN` in Oregon material, and a scanner
that merely counted short forms without this guard would rank an Oregon criminal statute as
the most-demanded section of the HIPAA Privacy Rule.

WHY COMMIT THE RESULT INSTEAD OF COMPUTING IT AT BUILD TIME: CI for this repo cannot reach
executive-regulatory-frameworks or oregon-audits -- they are separate repositories and are
not checked out. A build-time scan would silently find zero citations there and split nothing,
which is the failure mode this platform keeps producing: a step that reports success while
doing nothing. So the scan runs on a developer machine, against real checkouts, and its output
is a reviewable artifact.

A CITED SECTION THAT NO LONGER EXISTS IS A FINDING, NOT A DROP. Two of 2 CFR 200's 29 (200.53
and 200.62) were REMOVED from the CFR. Silently omitting them would leave four real citations
in Oregon's own audits pointing at nothing, and quietly resolving them to current text would
answer a compliance question with law that was not in force. Both are classified here from
eCFR's own version record -- `removed: true` plus an amendment date -- and carried into the
corpus as superseded documents holding their last-in-force text.

STANDING TRIGGER FOR THE OTHER BIG INSTRUMENTS (recorded 2026-08-03): WIOA,
Perkins V, CJIS and Pub 1075 were measured at ZERO section-shaped citations,
so they got `### ` anchors (src/anchor_sections.py) instead of section
documents. The day a scan like this one finds section-shaped citations to any
of them in the citing corpora, that instrument graduates to the demand-driven
split exactly as it did for 2 CFR 200 -- same pipeline, same review gate.
Anchors first, documents when demanded. (This is a CFR-part-shaped scan; WIOA and
Perkins V are public laws with `SEC. N.` numbering, not `title CFR part.section`, so
graduating one of those needs a citation-shape scan of its own, not this script.)

#63: ONE LEVEL UP FROM THIS SCRIPT'S ORIGINAL QUESTION. `--title`/`--part` answer "which
sections of THIS part does Oregon cite" only after a human has already picked the part --
#22 through #25 did that picking by hand, and #63's own measurement showed none of #22's
four candidates carries a single authority claim while the largest unheld part (34 CFR
300, 105 claims) appeared in no candidate issue. Passing NEITHER `--title` NOR `--part`
switches this script into PART-DISCOVERY MODE: it ranks UNHELD CFR parts by authority
claim instead of splitting one already-chosen part into sections. Same operator ("which
federal thing does this corpus need next"), same demand-driven trigger ADR-0003 already
uses for sections, one level up: writes `_meta/ingest-queue.yml` (see that file's own
header for its schema and the reason it, too, is committed rather than computed).

    python3 src/scan_cited_sections.py --erf ../executive-regulatory-frameworks --audits ../oregon-audits

PART-DISCOVERY MODE READS ERF'S OWN CATALOG RATHER THAN RE-DERIVING CLAIMS AND MENTIONS
FROM RAW TEXT A SECOND TIME. `--audits` is still required for CLI symmetry with the
per-part mode above and is validated as a directory, but its content is not scanned here:
`executive-regulatory-frameworks/_meta/catalog/external-citations.yml`, generated by ITS
OWN `src/scan_external_citations.py`, already walks every ERF document, already separates
a `legal_authority`/`statutes_implemented` frontmatter entry (a CLAIM) from a body-text
occurrence (a MENTION), and is committed and reviewed there for exactly the reason
`_meta/cited-sections/<part>.yml` is committed here. Every worked example in #63's own
spec text -- 34 CFR 300 (105 claims), 7 CFR 273 (33), 34 CFR 99 (27), 34 CFR 303 (20),
49 CFR 1520 (19), 42 CFR Part 2 (0 claims, 39 mentions) -- is that catalog's own number,
verified by reading it directly (see `_meta/ingest-queue.yml`'s header for the command).
Re-implementing the same title/CFR/section extraction and claim-vs-mention split here
a second time is exactly the shape of bug this corpus keeps naming as a defect elsewhere
(`federal_ids.py`'s docstring: "a second copy here would be a fourth thing to keep
byte-identical") -- oregon-audits carries no `legal_authority` concept at all (checked:
one stray hit, in prose describing the field, not an actual frontmatter key), so it has
nothing to contribute to either count and is correctly left unscanned in this mode.

HELD-NESS IS NEVER READ FROM ERF'S CATALOG. Its own `resolves` field reflects what ERF's
last regeneration believed federal-reference held, which can go stale the moment either
repo moves. A part here counts as held only if THIS corpus's own `instruments/` carries
a `cfr_part` document for it or any `cfr_section` sliced from it -- recomputed fresh from
the documents on disk every run, the same source `citation_schemes.HELD` is built from
(see that file's docstring), never a second list that could disagree with what is really
ingested.
"""
from __future__ import annotations

import argparse
import collections
import json
import pathlib
import re
import sys
import urllib.request

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "_meta" / "cited-sections"
INSTRUMENTS = ROOT / "instruments"
QUEUE_OUT = ROOT / "_meta" / "ingest-queue.yml"
ERF_CATALOG_REL = pathlib.Path("_meta") / "catalog" / "external-citations.yml"

SKIP_PARTS = ("/.git/", "/_meta/", "/snapshots/", "/node_modules/")


def patterns(title: int, part: int) -> tuple[re.Pattern, re.Pattern, re.Pattern]:
    """(section_re, short_re, part_re) for one (title, part) -- built, not hardcoded.

    section_re: "2 CFR 200.303", "2 C.F.R. § 200.303", "2 CFR Part 200.303", "2 CFR §§ 200.303".
    Anchored on the literal title and part: a general CFR-citation regex here would quietly
    collect sections of parts this corpus does not hold.

    short_re: THE SHORT FORM, which section_re cannot see and which is how real documents
    actually cite. A report names "2 CFR 200" once and then writes "§200.414" for the rest of
    the section. Requiring the literal "N CFR" on every hit hid 42 citations across 18
    sections for 2 CFR 200 alone, NINE of which had no document at all.

    part_re: a full part citation anywhere in the file, which licenses the short form above.
    ONLY COUNTED IN FILES THAT ALSO CARRY A FULL CITATION -- a bare `§NNN.MM` is ambiguous on
    its own (Oregon's own ORS numbering collides with plenty of CFR part numbers -- chapter
    200, chapter 164 -- see this file's module docstring), so the full citation elsewhere in
    the same document is what establishes which title/part the short form refers to.
    """
    t, p = re.escape(str(title)), re.escape(str(part))
    section_re = re.compile(
        rf"\b{t}\s+C\.?\s?F\.?\s?R\.?\s*(?:Part\s+)?§{{0,2}}\s*{p}\.(\d+)\b")
    short_re = re.compile(rf"§{{1,2}}\s*{p}\.(\d+)\b")
    part_re = re.compile(rf"\b{t}\s+C\.?\s?F\.?\s?R\.?\s*(?:Part\s+)?§{{0,2}}\s*{p}\b")
    return section_re, short_re, part_re


def scan(root: pathlib.Path, label: str, section_re, short_re, part_re, counts, sources) -> int:
    """Count section citations under `root`. Returns files scanned."""
    n = 0
    # SORTED walk. An unsorted rglob in the ERF citation scan produced a catalog that
    # differed between machines while every count matched -- only CI could see it.
    for path in sorted(root.rglob("*.md")):
        s = str(path)
        if any(p in s for p in SKIP_PARTS):
            continue
        n += 1
        text = path.read_text(errors="ignore")
        full_matches = list(section_re.finditer(text))
        hits = [m.group(1) for m in full_matches]
        if hits or part_re.search(text):
            # The short form only counts once this file has established the part. A
            # short-form hit whose span falls INSIDE a full-citation match is the same
            # occurrence counted twice -- section_re optionally allows the `§`, so
            # "34 CFR § 300.8" satisfies both regexes at the same position. Keep only
            # short-form hits that are not already covered by a full match.
            full_spans = [m.span() for m in full_matches]
            for m in short_re.finditer(text):
                if not any(lo <= m.start() and m.end() <= hi for lo, hi in full_spans):
                    hits.append(m.group(1))
        for sec in hits:
            counts[sec] += 1
            sources[sec].add(label)
    return n


def ecfr_versions(title: int, part: int) -> dict[str, dict]:
    """eCFR's own version record per section: {'200.53': {...}}.

    This is the authority for whether a section still exists. Reading it beats inferring
    absence from the current text: absence tells you a section is gone, this tells you WHEN
    it went and whether it was removed or merely renumbered.
    """
    url = f"https://www.ecfr.gov/api/versioner/v1/versions/title-{title}.json?part={part}"
    data = json.loads(urllib.request.urlopen(url, timeout=180).read())
    out: dict[str, dict] = {}
    for rec in data.get("content_versions") or data.get("versions") or []:
        ident = rec.get("identifier")
        if not ident:
            continue
        prev = out.get(ident)
        # Keep the LATEST record per section -- that is the one that says whether it is
        # still here. Records arrive oldest-first but that is not promised, so compare.
        if prev is None or (rec.get("amendment_date") or "") >= (prev.get("amendment_date") or ""):
            out[ident] = rec
    return out


def q(s: str) -> str:
    return json.dumps(str(s), ensure_ascii=False)


# The lines of a cited-sections YAML that depend ONLY on (title, part), never on a scan's
# results -- pulled out so split_cfr_sections.py --check can verify a committed file's header
# has not drifted from what THIS script would write for the same part, without re-running the
# scan itself (which needs the sibling repos CI cannot reach; see the module docstring). A
# `_meta/cited-sections/2-cfr-200.yml` was once `git mv`'d without being regenerated and kept
# advertising a `--erf/--audits` command with no `--title`/`--part` for months, uncaught,
# because nothing compared the committed header against its own generator.
CURRENT_COMMENT = "# Sections still in force. Text comes from the committed current part snapshot."
REMOVED_COMMENT = [
    "# REMOVED from the CFR, but still cited by Oregon material. These carry their",
    "# LAST-IN-FORCE text from a point-in-time snapshot, marked superseded. Resolving one",
    "# of these to current text would answer with law that was not in force when it was",
    "# cited -- a wrong answer wearing a right answer's clothes.",
]
# A section citation with NO eCFR version record at all -- distinct from `removed`, which
# HAS a record (`removed: true` plus an amendment date). No record means eCFR's versioner
# never tracked this identifier under this part, which happens when a part was recodified
# wholesale (34 CFR 300's own SOURCE line: "71 FR 46753, Aug. 14, 2006" -- a full-part
# renumbering) and an Oregon citation was never updated past the old numbering. There is no
# snapshot to slice a document from without fabricating text AGENTS.md forbids, so these are
# named here -- a real Oregon citation pointing at nothing -- and never split.
UNRESOLVABLE_COMMENT = [
    "# NO eCFR version record at all -- not current, not a recorded removal. Most likely a",
    "# pre-recodification section number eCFR's versioner never tracked (see this part's own",
    "# SOURCE line for its recodification date) that an Oregon citation was never updated",
    "# past. Cannot be split: there is no snapshot to cut a document from. A real citation",
    "# pointing at nothing, named rather than silently dropped -- see ADR-0003.",
]


def static_header(title: int, part: int) -> list[str]:
    """The top comment block -- everything before `scanned_files:` -- for one (title, part)."""
    return [
        "# GENERATED by src/scan_cited_sections.py -- do not hand-edit.",
        "#",
        f"# Which sections of {title} CFR {part} get their own document, and why "
        f"each one is here.",
        "# Regenerate with:",
        f"#   python3 src/scan_cited_sections.py --erf ../executive-regulatory-frameworks "
        f"--audits ../oregon-audits --title {title} --part {part}",
        "#",
        "# Committed rather than computed during the build because CI cannot reach the sibling",
        "# repositories this is derived from; a build-time scan would find zero and split nothing.",
    ]


# --------------------------------------------------------------------- part-discovery (#63)

CFR_CITATION_RE = re.compile(r"^(\d{1,3}) CFR (\d+[A-Za-z]?)$")


def parse_cfr_citation(citation: str) -> tuple[str, str] | None:
    """(title, part) if `citation` is a bare CFR-part-shaped string ("34 CFR 300"), else
    None -- USC citations and the catalog's `named_instruments` (HIPAA, WIOA, ...) are not
    CFR-part-rankable the same way and are correctly excluded here, not filtered upstream.

    A FORMAT CHECK, NOT A SECOND PARSER: ERF's own src/scan_external_citations.py already
    normalizes every hit to exactly this shape (its `norm()`) before writing the catalog --
    section suffixes are already collapsed into the part there. Verified against the real
    catalog: all 575 of its CFR-looking `citation` strings match this pattern, including
    the two with a letter-suffixed part ("7 CFR 1c", "8 CFR 274a")."""
    m = CFR_CITATION_RE.match(citation)
    return (m.group(1), m.group(2)) if m else None


def held_cfr_parts(instruments: pathlib.Path = INSTRUMENTS) -> set[tuple[str, str]]:
    """{(title, part)} for every CFR part THIS corpus already holds -- whole or by section.

    ADR-0003: a part can be split into sections with no document left for the bare part id
    (2 CFR 200 itself still has one, but the rule is general), so a part counts as held if
    `instruments/` carries a `cfr_part` document for it OR any `cfr_section` sliced from it.

    Read from frontmatter actually on disk -- the same source `citation_schemes.HELD` is
    built from (see that module's `_held()` docstring) -- never a second, hand-maintained
    list that could disagree with what is really ingested. Deliberately does NOT import
    citation_schemes: importing it registers MCP citation schemes as a side effect, which
    this scan has no business triggering."""
    out: set[tuple[str, str]] = set()
    if not instruments.is_dir():
        return out
    for path in sorted(instruments.glob("*.md")):
        head = path.read_text(encoding="utf-8").split("---", 2)
        if len(head) < 3:
            continue
        fm = yaml.safe_load(head[1]) or {}
        if fm.get("instrument_kind") not in ("cfr_part", "cfr_section"):
            continue
        doc_id = str(fm.get("id") or "")
        if "-cfr-" not in doc_id:
            continue
        title, rest = doc_id.split("-cfr-", 1)
        part = rest.split(".", 1)[0]
        out.add((title, part))
    return out


def rank_targets(targets: list[dict], held: set[tuple[str, str]]) -> list[dict]:
    """Unheld CFR parts from ERF's catalog `targets:` list, ranked by AUTHORITY CLAIM.

    CONTEXT.md: "a claim is a rule naming the instrument as its legal authority; a mention
    is any reference in prose." Ranking is claims-desc, mentions only breaking ties -- never
    promoted above claims -- so a part like 42 CFR Part 2 (0 claims, dozens of mentions)
    sinks to the bottom of the ranking without ever being DROPPED from it: every entry
    still carries its own `mentions`, so the human sees both numbers, exactly as #63 story 3
    asks, rather than the ranking silently making that case for or against 42 CFR Part 2.
    """
    rows = []
    for t in targets:
        parsed = parse_cfr_citation(str(t.get("citation", "")))
        if parsed is None:
            continue
        title, part = parsed
        if (title, part) in held:
            continue
        rows.append({
            "part_id": f"{title}-cfr-{part}",
            "citation": f"{title} CFR {part}",
            "title": title,
            "part": part,
            "authority_claims": int(t.get("authority_claims", 0)),
            "mentions": int(t.get("mentions", 0)),
        })
    rows.sort(key=lambda r: (-r["authority_claims"], -r["mentions"], r["part_id"]))
    return rows


def queue_header() -> list[str]:
    """The top comment block -- everything before `scanned_targets:` -- for the ingest
    queue. Mirrors `static_header()` above: a GENERATED notice, the verbatim regeneration
    command, and the reason the file is committed rather than computed, quoted (not
    paraphrased, per #63) from this module's own docstring."""
    return [
        "# GENERATED by src/scan_cited_sections.py -- do not hand-edit.",
        "#",
        "# Unheld CFR parts Oregon cites, ranked by authority claim -- which federal part",
        "# to ingest next, DERIVED rather than curated by hand (federal-reference#63).",
        "# Regenerate with:",
        "#   python3 src/scan_cited_sections.py --erf ../executive-regulatory-frameworks "
        "--audits ../oregon-audits",
        "#",
        "# Committed rather than computed during the build for the same reason every",
        "# _meta/cited-sections/<part>.yml is -- quoted verbatim from this file's own",
        "# module docstring: \"CI for this repo cannot reach executive-regulatory-frameworks",
        "# or oregon-audits -- they are separate repositories and are not checked out. A",
        "# build-time scan would silently find zero citations there and split nothing,",
        "# which is the failure mode this platform keeps producing: a step that reports",
        "# success while doing nothing.\"",
        "#",
        "# RANKED BY AUTHORITY CLAIM, mentions carried alongside -- CONTEXT.md: \"a claim is",
        "# a rule naming the instrument as its legal authority; a mention is any reference",
        "# in prose.\" Source: executive-regulatory-frameworks's own",
        "# _meta/catalog/external-citations.yml, generated by ITS OWN",
        "# src/scan_external_citations.py and committed there for the identical reason.",
        "# Held-ness is read fresh from THIS corpus's instruments/ at generation time, never",
        "# from that catalog's own (potentially stale) `resolves` field.",
        "#",
        "# `catalog_targets_total` is EVERY target in ERF's catalog, CFR and non-CFR alike.",
        "# `scanned_targets` below is the CFR-shaped SUBSET of it (parse_cfr_citation() --",
        "# USC citations and named instruments like HIPAA/WIOA are not CFR-part-rankable the",
        "# same way and are correctly excluded, not silently dropped from a total that claims",
        "# to be the whole catalog). `held_parts` counts held CFR parts AMONG THAT SUBSET --",
        "# a part this corpus holds that ERF's catalog never cites contributes nothing to it;",
        "# see held_cfr_parts() for the full held set this corpus actually carries.",
    ]


def q2(s) -> str:
    return json.dumps(s, ensure_ascii=False) if isinstance(s, str) else json.dumps(s)


def build_queue_lines(catalog: dict, held: set[tuple[str, str]]) -> tuple[list[str], int, int]:
    """Compute `_meta/ingest-queue.yml`'s content -- PURE, no I/O. Returns (lines,
    unheld_parts, total_cfr_targets) so the caller can decide whether to write it and what
    to report. Raises nothing; a catalog with zero CFR targets is the caller's refusal to
    make, not this function's (see the module docstring: zero found is a REFUSAL, not an
    empty queue) -- and specifically NOT this function's job to act on by touching
    `QUEUE_OUT`, which is why this function touches no path at all."""
    targets = catalog.get("targets") or []
    all_cfr = [(t, parse_cfr_citation(str(t.get("citation", ""))))
               for t in targets]
    all_cfr = [(t, p) for t, p in all_cfr if p is not None]
    held_targets = [t for t, p in all_cfr if p in held]
    ranked = rank_targets(targets, held)

    claims_all = sum(int(t.get("authority_claims", 0)) for t, _ in all_cfr)
    claims_held = sum(int(t.get("authority_claims", 0)) for t in held_targets)
    claims_unheld = sum(r["authority_claims"] for r in ranked)

    lines = queue_header() + [
        "",
        f"catalog_targets_total: {len(targets)}",
        f"scanned_targets: {len(all_cfr)}",
        f"held_parts: {len(all_cfr) - len(ranked)}",
        f"unheld_parts: {len(ranked)}",
        f"total_authority_claims_all_parts: {claims_all}",
        f"total_authority_claims_held: {claims_held}",
        "# Denominator for \"we hold the top N\": how many of the claims below a maintainer",
        "# would account for by ingesting the first N entries of `queue:`.",
        f"total_authority_claims_unheld: {claims_unheld}",
        "",
        "queue:",
    ]
    for r in ranked:
        lines += [f"  - part_id: {q2(r['part_id'])}",
                  f"    citation: {q2(r['citation'])}",
                  f"    authority_claims: {r['authority_claims']}",
                  f"    mentions: {r['mentions']}"]
    return lines, len(ranked), len(all_cfr)


def write_queue(lines: list[str]) -> None:
    """The only place `QUEUE_OUT` is written. Separated from `build_queue_lines()` so a
    zero-result refusal (see `discover_main()`) can return before this ever runs, instead
    of overwriting -- or, worse, deleting -- a committed, reviewed artifact as a side
    effect of an error path."""
    QUEUE_OUT.parent.mkdir(parents=True, exist_ok=True)
    QUEUE_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def discover_main(args: argparse.Namespace) -> int:
    """Part-discovery mode: `--title`/`--part` both omitted. See the module docstring's
    #63 section for why this reads ERF's own catalog instead of re-deriving claims and
    mentions from raw text a second time."""
    if not args.erf.is_dir():
        print(f"error: {args.erf} is not a directory", file=sys.stderr)
        return 1
    if not args.audits.is_dir():
        # Validated for CLI symmetry with the per-part mode; not scanned in this mode --
        # see the module docstring's #63 section for why oregon-audits has nothing to
        # contribute to either count here.
        print(f"error: {args.audits} is not a directory", file=sys.stderr)
        return 1

    catalog_path = args.erf / ERF_CATALOG_REL
    if not catalog_path.is_file():
        print(f"error: {catalog_path} not found -- run "
              f"executive-regulatory-frameworks's own src/scan_external_citations.py first; "
              f"this corpus's ingest queue is DERIVED FROM that catalog, not a second "
              f"re-derivation of it", file=sys.stderr)
        return 1
    catalog = yaml.safe_load(catalog_path.read_text(encoding="utf-8")) or {}
    targets = catalog.get("targets") or []
    print(f"  read {len(targets)} targets from {catalog_path}")

    held = held_cfr_parts()
    print(f"  {len(held)} CFR part(s) already held")

    lines, unheld_n, total_n = build_queue_lines(catalog, held)
    if unheld_n == 0:
        # Matches the per-part mode's own refusal a few lines up: a scan that finds nothing
        # to rank is either a broken scan (wrong --erf path, stale catalog) or every CFR
        # part Oregon cites is already held, and the caller decides which -- this script
        # only reports the fact rather than writing an empty artifact that looks derived.
        #
        # CRITICALLY: nothing above this point has touched `QUEUE_OUT`. A committed,
        # reviewed queue survives a broken --erf path, a stale sibling catalog, or the
        # genuine "everything is held now" state untouched -- retiring it is a deliberate,
        # separate action for a maintainer to take, never an automatic side effect of this
        # script finding nothing to rank.
        print(f"error: no unheld CFR parts found among {total_n} CFR targets in ERF's "
              f"catalog -- check the --erf path, or every cited CFR part is already held",
              file=sys.stderr)
        return 1
    write_queue(lines)
    print(f"  wrote {QUEUE_OUT.relative_to(ROOT)}: {unheld_n} unheld of {total_n} CFR parts")
    return 0


def check_queue() -> int:
    """`--check`: does the COMMITTED `_meta/ingest-queue.yml` still agree with itself and
    with THIS corpus's own instruments/ -- header current, ranking correctly ordered,
    every declared summary number self-consistent, and no listed part actually held?

    WHAT THIS DELIBERATELY DOES NOT DO: re-read ERF's catalog or re-rank from it. That
    would need `--erf` pointed at a real sibling checkout, which is exactly what CI cannot
    do (see the module docstring's WHY COMMIT section) -- a `--check` that tried would
    either fail on every PR for a reason that is not drift, or silently skip itself in CI
    and verify nothing while its name claims it does, which is the identical failure this
    whole file's docstring calls out. So this checks what CI CAN honestly verify without a
    sibling checkout: the committed file's own internal consistency, its header, and its
    agreement with the LOCAL instruments/ directory -- and says so in its own output,
    rather than silently verifying less than `--check` sounds like it does. Full
    re-derivation against a fresh scan stays the developer-machine step it already was.
    """
    problems: list[str] = []
    if not QUEUE_OUT.is_file():
        print(f"error: {QUEUE_OUT} does not exist -- run "
              f"src/scan_cited_sections.py --erf ... --audits ... first", file=sys.stderr)
        return 1

    raw = QUEUE_OUT.read_text(encoding="utf-8")
    raw_lines = raw.splitlines()
    expected_header = queue_header()
    if raw_lines[:len(expected_header)] != expected_header:
        problems.append("the top comment block (regenerate command / commit-reason / "
                         "ranking-rule text) does not match what queue_header() writes today")

    doc = yaml.safe_load(raw) or {}
    queue = doc.get("queue") or []

    # Shape: every entry carries the four fields write_queue() writes, with the types it
    # writes them as -- a hand-edit that drops a field or changes a type is drift too.
    for i, e in enumerate(queue):
        missing = [k for k in ("part_id", "citation", "authority_claims", "mentions")
                   if k not in e]
        if missing:
            problems.append(f"queue[{i}] ({e.get('part_id', '?')}) missing field(s): "
                             f"{', '.join(missing)}")

    # Sort order: claims desc, mentions desc, part_id asc -- exactly rank_targets()'s key,
    # checked against the COMMITTED rows themselves rather than re-ranking from a live
    # catalog this mode cannot reach.
    keyed = [(-e.get("authority_claims", 0), -e.get("mentions", 0), e.get("part_id", ""))
             for e in queue]
    if keyed != sorted(keyed):
        problems.append("queue: is not sorted by authority_claims desc, mentions desc, "
                         "part_id asc")

    # Held-ness, recomputed fresh from THIS corpus's own instruments/ -- the one fact this
    # check CAN verify without a sibling checkout, and the one most likely to rot silently:
    # ingest a part from the top of the queue and forget to regenerate, and the queue keeps
    # recommending work already done.
    held = held_cfr_parts()
    for e in queue:
        pid = str(e.get("part_id", ""))
        if "-cfr-" not in pid:
            problems.append(f"queue entry has a malformed part_id: {pid!r}")
            continue
        key = tuple(pid.split("-cfr-", 1))
        if key in held:
            problems.append(f"queue[{pid}] is listed as unheld but instruments/ now "
                             f"holds {key[0]} CFR {key[1]}")

    # Declared summary numbers, checked against the queue's OWN rows -- self-consistency,
    # not a re-scan.
    unheld_parts = int(doc.get("unheld_parts", -1))
    if unheld_parts != len(queue):
        problems.append(f"unheld_parts: {unheld_parts} does not match {len(queue)} "
                         f"queue entries")
    claims_unheld = int(doc.get("total_authority_claims_unheld", -1))
    summed = sum(int(e.get("authority_claims", 0)) for e in queue)
    if claims_unheld != summed:
        problems.append(f"total_authority_claims_unheld: {claims_unheld} does not match "
                         f"the sum of queue entries' authority_claims ({summed})")
    scanned = int(doc.get("scanned_targets", -1))
    held_n = int(doc.get("held_parts", -1))
    if scanned != held_n + len(queue):
        problems.append(f"scanned_targets ({scanned}) does not equal "
                         f"held_parts ({held_n}) + unheld_parts ({len(queue)})")

    # The other two declared claim totals -- previously written but never verified, so a
    # hand-edit to either one passed this gate silently. Checked the same way as
    # total_authority_claims_unheld above: self-consistency against the OTHER declared
    # numbers in this same file, not a re-scan.
    claims_all = int(doc.get("total_authority_claims_all_parts", -1))
    claims_held = int(doc.get("total_authority_claims_held", -1))
    if claims_all != claims_held + claims_unheld:
        problems.append(f"total_authority_claims_all_parts ({claims_all}) does not equal "
                         f"total_authority_claims_held ({claims_held}) + "
                         f"total_authority_claims_unheld ({claims_unheld})")

    # catalog_targets_total is the whole catalog (CFR and non-CFR); scanned_targets is the
    # CFR-shaped subset build_queue_lines() actually ranks from. The subset can never
    # exceed the whole it was filtered out of.
    catalog_total = int(doc.get("catalog_targets_total", -1))
    if catalog_total < scanned:
        problems.append(f"catalog_targets_total ({catalog_total}) is less than "
                         f"scanned_targets ({scanned}) -- the CFR-shaped subset cannot "
                         f"exceed the catalog it was filtered from")

    if problems:
        for p in problems:
            print(f"  STALE  {p}", file=sys.stderr)
        print(f"\nRe-run: python3 src/scan_cited_sections.py --erf ../executive-regulatory-frameworks "
              f"--audits ../oregon-audits", file=sys.stderr)
        return 1
    print(f"  {QUEUE_OUT.relative_to(ROOT)}: header current, {len(queue)} entries "
          f"internally consistent, none held")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--erf", required=True, type=pathlib.Path)
    ap.add_argument("--audits", required=True, type=pathlib.Path)
    # #63: both optional now, but together, not separately. Neither given -> part-discovery
    # mode (rank unheld CFR parts instead of splitting one already-chosen part).
    ap.add_argument("--title", type=int, help="CFR title, e.g. 2 -- omit with --part for "
                     "part-discovery mode")
    ap.add_argument("--part", type=int, help="CFR part, e.g. 200 -- omit with --title for "
                     "part-discovery mode")
    ap.add_argument("--check", action="store_true",
                     help="verify the committed _meta/ingest-queue.yml against itself and "
                     "this corpus's own instruments/ -- part-discovery mode only; see "
                     "check_queue()'s docstring for exactly what this does and does not "
                     "verify")
    args = ap.parse_args()

    if (args.title is None) != (args.part is None):
        print("error: pass both --title and --part, or neither (neither = part-discovery "
              "mode)", file=sys.stderr)
        return 1
    if args.title is None:
        if args.check:
            return check_queue()
        return discover_main(args)
    if args.check:
        print("error: --check applies to part-discovery mode only (omit --title/--part) "
              "-- the per-part cited-sections file is checked by "
              "src/split_cfr_sections.py --check instead", file=sys.stderr)
        return 1

    part_id = f"{args.title}-cfr-{args.part}"
    out = OUT_DIR / f"{part_id}.yml"
    section_re, short_re, part_re = patterns(args.title, args.part)
    part_prefix = str(args.part)

    counts: collections.Counter = collections.Counter()
    sources: dict[str, set] = collections.defaultdict(set)
    total_files = 0
    for root, label in ((args.erf, "erf"), (args.audits, "audits")):
        if not root.is_dir():
            print(f"error: {root} is not a directory", file=sys.stderr)
            return 1
        got = scan(root, label, section_re, short_re, part_re, counts, sources)
        total_files += got
        print(f"  scanned {got:>5} files in {root}  ({label})")

    if not counts:
        # A scan that finds nothing is either a broken scan or a part that graduates no
        # further than the anchors it already has -- the caller decides which; this script
        # only reports the fact rather than writing an empty artifact that looks derived.
        print(f"error: no {args.title} CFR {args.part} section citations found -- check the "
              f"paths, or this part does not (yet) meet the demand-driven split trigger",
              file=sys.stderr)
        return 1

    print(f"  {sum(counts.values())} citations across {len(counts)} distinct sections")
    vers = ecfr_versions(args.title, args.part)
    print(f"  eCFR version record: {len(vers)} sections")

    current, removed, unresolvable = [], [], []
    for sec, n in sorted(counts.items(), key=lambda kv: (-kv[1], int(kv[0]))):
        rec = vers.get(f"{part_prefix}.{sec}")
        entry = {"section": f"{part_prefix}.{sec}", "citations": n,
                 "cited_in": sorted(sources[sec])}
        if rec is None:
            print(f"warning: {part_prefix}.{sec} has no eCFR version record at all -- "
                  f"a real citation pointing at nothing, named in the unresolvable: "
                  f"section rather than dropped", file=sys.stderr)
            unresolvable.append(entry)
        elif rec.get("removed"):
            entry["removed_on"] = rec["amendment_date"]
            entry["name_when_in_force"] = " ".join(str(rec.get("name") or "").split())
            removed.append(entry)
        else:
            current.append(entry)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    lines = static_header(args.title, args.part) + [
        "",
        f"scanned_files: {total_files}",
        f"total_citations: {sum(counts.values())}",
        "",
        CURRENT_COMMENT,
        "current:",
    ]
    for e in current:
        lines += [f"  - section: {q(e['section'])}",
                  f"    citations: {e['citations']}",
                  f"    cited_in: [{', '.join(q(c) for c in e['cited_in'])}]"]
    lines += [""] + REMOVED_COMMENT + ["removed:"]
    for e in removed:
        lines += [f"  - section: {q(e['section'])}",
                  f"    citations: {e['citations']}",
                  f"    cited_in: [{', '.join(q(c) for c in e['cited_in'])}]",
                  f"    removed_on: {q(e['removed_on'])}",
                  f"    name_when_in_force: {q(e['name_when_in_force'])}"]
    lines += [""] + UNRESOLVABLE_COMMENT + ["unresolvable:"]
    for e in unresolvable:
        lines += [f"  - section: {q(e['section'])}",
                  f"    citations: {e['citations']}",
                  f"    cited_in: [{', '.join(q(c) for c in e['cited_in'])}]"]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote {out.relative_to(ROOT)}: {len(current)} current, {len(removed)} removed, "
          f"{len(unresolvable)} unresolvable")
    for e in removed:
        print(f"      removed {e['section']} on {e['removed_on']} ({e['citations']} citations)")
    for e in unresolvable:
        print(f"      unresolvable {e['section']} -- no eCFR version record "
              f"({e['citations']} citations, in {', '.join(e['cited_in'])})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
